<a href="https://colab.research.google.com/github/chaitanyasatyasai/oasiswork/blob/main/DWM_pd%26np.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

**1)Different ways to create a Numpy arrays.**

In [ ]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b.ndim

2

In [ ]:
c=np.arange(10,30,5)
c

array([10, 15, 20, 25])

**2) Add, remove, modify elements in an array.**
**2.1) Adding elements to an array **

In [ ]:
x=np.append(b,[10,3,8])
x

array([ 1,  2,  3,  4,  5,  6, 10,  3,  8])

**2.2) Remove element/s from an array**

In [ ]:
print("before deleting the elements",x)
newx = np.delete(x,7)
print("after deleting element")
newx

before deleting the elements [ 1  2  3  4  5  6 10  3  8]
after deleting element


array([ 1,  2,  3,  4,  5,  6, 10,  8])

**2.3) Modify elements in the array**

In [ ]:
b[b<4] = -1
b

array([[-1, -1, -1],
       [ 4,  5,  6]])

**3) Arithmetic operations on NumPy array**

In [ ]:
d = np.array( [20,30,40,50] )
e = np.arange( 4 )
d

array([20, 30, 40, 50])

In [ ]:
e

array([0, 1, 2, 3])

In [ ]:
d+e

array([20, 31, 42, 53])

a-b

In [ ]:
d-e

array([20, 29, 38, 47])

In [ ]:
d*e

array([  0,  30,  80, 150])

In [ ]:
d/e

<ipython-input-27-cdd164382f43>:1: RuntimeWarning: divide by zero encountered in true_divide
  d/e


array([        inf, 30.        , 20.        , 16.66666667])

In [ ]:
e*5

array([ 0,  5, 10, 15])

In [ ]:

10*np.sin(e)

array([0.        , 8.41470985, 9.09297427, 1.41120008])

In [ ]:
g=np.array([1,2,3])
g[0]+=10
g

array([11,  2,  3])

In [ ]:
np.dot(d,e)

260

**4) Slicing and iterating of NumPy arrays**
**4.1) Slicing 1-D array**

In [ ]:
h=np.arange(10)**4
h

array([   0,    1,   16,   81,  256,  625, 1296, 2401, 4096, 6561])

In [ ]:
print(h[2])
print(h[2:4])
print(h[2:3])
print(h[-1])
print(h[-2])
print(h[-5:-2])

16
[16 81]
[16]
6561
4096
[ 625 1296 2401]


**4.2) Slicing 2-D array**

In [ ]:
k=np.arange(12).reshape(4,3)**2
k

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121]])

In [ ]:
print(k[1:3])
print(k[1:3,1:2])
print(k[2,])#second row
print(k[:3,])#upto last row
print(k[-1,])#last row
print(k[-1,-1])#last row &last column

[[ 9 16 25]
 [36 49 64]]
[[16]
 [49]]
[36 49 64]
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
[ 81 100 121]
121


**4.3) Iterating**

In [ ]:
j=np.arange(12).reshape(4,3)**2
j

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121]])

In [ ]:
for i in j:
  print(i*3)

[ 0  3 12]
[27 48 75]
[108 147 192]
[243 300 363]


**5)Matrix operations on NumPy arrays**

In [ ]:
a=np.floor(10*np.random.random((3,4)))
print(a)
print(a.reshape(2,6))
print(a.ravel())#flattend array
print(a.T)

[[0. 9. 9. 9.]
 [0. 1. 1. 7.]
 [0. 7. 9. 4.]]
[[0. 9. 9. 9. 0. 1.]
 [1. 7. 0. 7. 9. 4.]]
[0. 9. 9. 9. 0. 1. 1. 7. 0. 7. 9. 4.]
[[0. 0. 0.]
 [9. 1. 7.]
 [9. 1. 9.]
 [9. 7. 4.]]


**pandas**

In [ ]:
df=pd.DataFrame({"Roll No":["aiml1","aiml2","aiml3"],"name":["satya","sai","siddhu"]})
df

Roll No    name
0   aiml1   satya
1   aiml2     sai
2   aiml3  siddhu

In [ ]:
df=pd.read_csv("/content/Iris.csv")
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [ ]:
df.shape

(150, 6)

In [ ]:
df1=pd.read_csv("/content/sample_data/california_housing_train.csv")
df1.shape

(17000, 9)

In [ ]:
df1.isna().any()

longitude             False
latitude              False
housing_median_age    False
total_rooms           False
total_bedrooms        False
population            False
households            False
median_income         False
median_house_value    False
dtype: bool

In [ ]:
df["sai"]=df1["total_rooms"]
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species  \
0   1            5.1           3.5            1.4           0.2  Iris-setosa   
1   2            4.9           3.4            1.4           0.2  Iris-setosa   
2   3            4.7           3.2            1.3           0.2  Iris-setosa   
4   5            5.0           3.6            1.4           0.2  Iris-setosa   
5   6            5.4           3.9            1.7           0.4  Iris-setosa   

      sai  
0  5612.0  
1  7650.0  
2   720.0  
4  1454.0  
5  1387.0

In [ ]:
del df["sai"]
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df2=pd.DataFrame({'Id':[6],'SepalLengthCm':[6.3],'SepalWidthCm':[3.8],'PetalLengthCm':[1.7],'PetalWidthCm':[0.3],'Species':["Iris-setosa"]})
df2

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   6            6.3           3.8            1.7           0.3  Iris-setosa

In [ ]:
df=df.append(df2)
df.head()

<ipython-input-25-d00c63305a6f>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df=df.append(df2)


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df=df.drop(3)
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa

In [ ]:
df.loc[1,'SepalWidthCm']=3.4
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.4            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa

In [ ]:
def incre(x):
  if(x<5.0):
     return(x-0.1)
  else:
    return(x)

In [ ]:
df["SepalLengthCm"]=df["SepalLengthCm"].apply(incre)
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species  \
0   1            5.1           3.5            1.4           0.2  Iris-setosa   
1   2            4.8           3.4            1.4           0.2  Iris-setosa   
2   3            4.6           3.2            1.3           0.2  Iris-setosa   
4   5            5.0           3.6            1.4           0.2  Iris-setosa   
5   6            5.4           3.9            1.7           0.4  Iris-setosa   

      sai  
0  5612.0  
1  7650.0  
2   720.0  
4  1454.0  
5  1387.0

In [ ]:
for index,rows in df[df['SepalLengthCm']>=4.8].iterrows():
  print(rows["Id"],"-",rows["SepalLengthCm"])

1 - 5.1
2 - 4.800000000000001
5 - 5.0
6 - 5.4
8 - 5.0
10 - 4.800000000000001
11 - 5.4
15 - 5.8
16 - 5.7
17 - 5.4
18 - 5.1
19 - 5.7
20 - 5.1
21 - 5.4
22 - 5.1
24 - 5.1
26 - 5.0
27 - 5.0
28 - 5.2
29 - 5.2
32 - 5.4
33 - 5.2
34 - 5.5
35 - 4.800000000000001
36 - 5.0
37 - 5.5
38 - 4.800000000000001
40 - 5.1
41 - 5.0
44 - 5.0
45 - 5.1
47 - 5.1
49 - 5.3
50 - 5.0
51 - 7.0
52 - 6.4
53 - 6.9
54 - 5.5
55 - 6.5
56 - 5.7
57 - 6.3
58 - 4.800000000000001
59 - 6.6
60 - 5.2
61 - 5.0
62 - 5.9
63 - 6.0
64 - 6.1
65 - 5.6
66 - 6.7
67 - 5.6
68 - 5.8
69 - 6.2
70 - 5.6
71 - 5.9
72 - 6.1
73 - 6.3
74 - 6.1
75 - 6.4
76 - 6.6
77 - 6.8
78 - 6.7
79 - 6.0
80 - 5.7
81 - 5.5
82 - 5.5
83 - 5.8
84 - 6.0
85 - 5.4
86 - 6.0
87 - 6.7
88 - 6.3
89 - 5.6
90 - 5.5
91 - 5.5
92 - 6.1
93 - 5.8
94 - 5.0
95 - 5.6
96 - 5.7
97 - 5.7
98 - 6.2
99 - 5.1
100 - 5.7
101 - 6.3
102 - 5.8
103 - 7.1
104 - 6.3
105 - 6.5
106 - 7.6
107 - 4.800000000000001
108 - 7.3
109 - 6.7
110 - 7.2
111 - 6.5
112 - 6.4
113 - 6.8
114 - 5.7
115 - 5.8
116 - 6.4
117 